-- ============================================================
--  Digital Farmer Assistance System — Full Database Schema
--  ⚠️  SAFE TO RE-RUN: Uses IF NOT EXISTS + INSERT IGNORE
--      so existing data (registered farmers, etc.) is NEVER lost.
-- ============================================================

CREATE DATABASE IF NOT EXISTS farmer_db;
USE farmer_db;

-- ── ADMIN ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ADMIN (
    admin_id    INT          PRIMARY KEY AUTO_INCREMENT,
    name        VARCHAR(100) NOT NULL,
    role        ENUM('superadmin','editor','viewer') NOT NULL DEFAULT 'editor',
    email       VARCHAR(150) UNIQUE NOT NULL,
    password    VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

-- ── FARMER ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS FARMER (
    farmer_id       INT          PRIMARY KEY AUTO_INCREMENT,
    name            VARCHAR(100) NOT NULL,
    phone           VARCHAR(15)  UNIQUE NOT NULL,
    region          VARCHAR(100) NOT NULL,
    language_pref   VARCHAR(10)  NOT NULL DEFAULT 'en',
    password        VARCHAR(255) NOT NULL,
    preferred_crops VARCHAR(255),
    created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

-- ── QUERY ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS QUERY (
    query_id       INT          PRIMARY KEY AUTO_INCREMENT,
    subject        VARCHAR(200) NOT NULL,
    description    TEXT         NOT NULL,
    status         ENUM('pending','answered','closed') DEFAULT 'pending',
    submitted_date DATE         NOT NULL DEFAULT (CURRENT_DATE),
    response       TEXT,
    farmer_id      INT          NOT NULL,
    admin_id       INT,
    FOREIGN KEY (farmer_id) REFERENCES FARMER(farmer_id) ON DELETE CASCADE,
    FOREIGN KEY (admin_id)  REFERENCES ADMIN(admin_id)   ON DELETE SET NULL
);

-- ── ADVISORY ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ADVISORY (
    adv_id       INT          PRIMARY KEY AUTO_INCREMENT,
    crop_type    VARCHAR(100) NOT NULL,
    season       VARCHAR(50)  NOT NULL,
    growth_stage VARCHAR(100),
    content      TEXT         NOT NULL,
    language     VARCHAR(10)  DEFAULT 'en',
    last_updated TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    admin_id     INT          NOT NULL,
    FOREIGN KEY (admin_id) REFERENCES ADMIN(admin_id) ON DELETE RESTRICT
);

-- ── MARKET_PRICE ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS MARKET_PRICE (
    price_id      INT            PRIMARY KEY AUTO_INCREMENT,
    crop_name     VARCHAR(100)   NOT NULL,
    current_price DECIMAL(10,2)  NOT NULL,
    prev_price    DECIMAL(10,2),
    source_market VARCHAR(150)   NOT NULL,
    state         VARCHAR(100)   DEFAULT 'Kerala',
    date_updated  DATE           NOT NULL DEFAULT (CURRENT_DATE),
    admin_id      INT            NOT NULL,
    FOREIGN KEY (admin_id) REFERENCES ADMIN(admin_id) ON DELETE RESTRICT
);

-- ── WEATHER_FORECAST ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS WEATHER_FORECAST (
    fc_id             INT            PRIMARY KEY AUTO_INCREMENT,
    location          VARCHAR(150)   NOT NULL,
    temperature       DECIMAL(5,2)   NOT NULL,
    feels_like        DECIMAL(5,2),
    humidity          INT,
    wind_speed        DECIMAL(6,2),
    weather_condition VARCHAR(100)   NOT NULL,
    is_extreme        BOOLEAN        DEFAULT FALSE,
    forecast_date     DATE           NOT NULL,
    fetched_at        TIMESTAMP      DEFAULT CURRENT_TIMESTAMP
);

-- ── SEED: ADMIN ────────────────────────────────────────────
-- password: admin123  (hash generated by bcryptjs v3)
-- INSERT IGNORE ensures existing admins (by unique email) are not duplicated
INSERT IGNORE INTO ADMIN (name, role, email, password) VALUES
('Ravi Kumar',   'superadmin', 'ravi@farmerassist.in',   '$2b$10$YQNJolh0GqIykKezI2dJVOMQSl7SEqkcCPqsNBZcnXT0A.OkqW6Zu'),
('Priya Nair',   'editor',     'priya@farmerassist.in',  '$2b$10$YQNJolh0GqIykKezI2dJVOMQSl7SEqkcCPqsNBZcnXT0A.OkqW6Zu'),
('Suresh Menon', 'viewer',     'suresh@farmerassist.in', '$2b$10$YQNJolh0GqIykKezI2dJVOMQSl7SEqkcCPqsNBZcnXT0A.OkqW6Zu');

-- ── SEED: FARMER ───────────────────────────────────────────
-- password: farmer123  (hash generated by bcryptjs v3)
-- INSERT IGNORE ensures existing farmers (by unique phone) are not duplicated
INSERT IGNORE INTO FARMER (name, phone, region, language_pref, password, preferred_crops) VALUES
('Annan Pillai',  '9876543210', 'Thrissur',  'en', '$2b$10$3KOp8B5IIgCPRfFfU9sBiuh//kvGsJbnCxtwzcUzWUvcgl0fw6Yra', 'Rice,Coconut'),
('Balan Nair',    '9123456780', 'Palakkad',  'en', '$2b$10$3KOp8B5IIgCPRfFfU9sBiuh//kvGsJbnCxtwzcUzWUvcgl0fw6Yra', 'Banana,Pepper'),
('Chandra Reddy', '9000011122', 'Ernakulam', 'en', '$2b$10$3KOp8B5IIgCPRfFfU9sBiuh//kvGsJbnCxtwzcUzWUvcgl0fw6Yra', 'Coconut');

-- ── SEED: ADVISORY ─────────────────────────────────────────
INSERT IGNORE INTO ADVISORY (crop_type, season, growth_stage, content, language, admin_id) VALUES
('Rice',    'Kharif', 'Tillering',  'Apply nitrogen fertilizer at tillering stage. Maintain 5 cm water level. Check for blast disease symptoms on leaves.', 'en', 1),
('Coconut', 'Annual', 'Mature',     'Check for Rhinoceros beetle infestation. Use pheromone traps near the base. Apply organic manure near root zone.', 'en', 2),
('Banana',  'Rabi',   'Flowering',  'Ensure proper drainage around plants. Apply potassium-rich compost before flowering. Watch for Panama wilt symptoms.', 'en', 1),
('Pepper',  'Kharif', 'Vegetative', 'Support vines with proper stakes. Spray Bordeaux mixture every 3 weeks to prevent Phytophthora rot.', 'en', 2),
('Tapioca', 'Annual', 'Growth',     'Earthing up is essential at 2 months. Apply potash fertilizer for better tuber development. Harvest at 8-10 months.', 'en', 1);

-- ── SEED: MARKET PRICE ─────────────────────────────────────
INSERT IGNORE INTO MARKET_PRICE (crop_name, current_price, prev_price, source_market, state, admin_id) VALUES
('Rice',    22.50,  21.00,  'Thrissur APMC',  'Kerala', 1),
('Coconut', 18.00,  17.50,  'Palakkad APMC',  'Kerala', 1),
('Banana',  35.00,  33.00,  'Ernakulam APMC', 'Kerala', 2),
('Pepper',  450.00, 430.00, 'Kozhikode APMC', 'Kerala', 2),
('Tapioca', 12.00,  11.50,  'Kollam APMC',    'Kerala', 1);

-- ── SEED: WEATHER ──────────────────────────────────────────
INSERT IGNORE INTO WEATHER_FORECAST (location, temperature, feels_like, humidity, wind_speed, weather_condition, is_extreme, forecast_date) VALUES
('Thrissur',  32.5, 35.0, 78, 12.0, 'Partly Cloudy', FALSE, CURRENT_DATE),
('Palakkad',  35.0, 38.0, 65, 15.0, 'Sunny',         FALSE, CURRENT_DATE),
('Ernakulam', 30.0, 33.0, 90,  8.0, 'Heavy Rain',    TRUE,  CURRENT_DATE),
('Kozhikode', 29.5, 32.0, 88, 10.0, 'Cloudy',        FALSE, CURRENT_DATE);

-- ── SEED: QUERIES ──────────────────────────────────────────
INSERT IGNORE INTO QUERY (subject, description, farmer_id, admin_id) VALUES
('Pest attack on rice', 'My rice crop has yellow leaves and brown spots. What should I do?', 1, 1),
('Market price query',  'What is the current price of coconut in Palakkad?', 2, NULL);

-- ── VIEWS ──────────────────────────────────────────────────
CREATE OR REPLACE VIEW latest_market_prices AS
    SELECT crop_name, current_price, prev_price, source_market, state, date_updated
    FROM MARKET_PRICE ORDER BY date_updated DESC;

CREATE OR REPLACE VIEW pending_queries AS
    SELECT q.query_id, f.name AS farmer_name, f.region, q.subject, q.submitted_date
    FROM QUERY q JOIN FARMER f ON q.farmer_id = f.farmer_id
    WHERE q.status = 'pending';

CREATE OR REPLACE VIEW extreme_weather_alerts AS
    SELECT location, temperature, weather_condition, forecast_date
    FROM WEATHER_FORECAST WHERE is_extreme = TRUE;
